### ISSUE TITLE
(Question) Will Integrated Intel UHD Graphics work?

### ISSUE THREAD

**Issue by c0d3rb0y** [jrbudda/Vivecraft_116#23]
Before i straight up buy a VR headset to play ViveCraft, i saw something about Intel HD Graphics not working. Does Intel UHD make any difference?

**Comment by GradiusLover2000** [comment]
Intel UHD is the same line as HD graphics just with "4K orientation".  the issue is ANY Intel GPU, even their dedicated cards.  it's a driver fault.

**Comment by c0d3rb0y** [comment]
oh. i'm currently on the NonVR version, does that have that problem or have I broken the rules of the code

**Comment by GradiusLover2000** [comment]
NonVR is just the vanilla client with multiplayer support to play with VR players and see their hands.  thus it is unaffected.  The Intel HD graphics bug is only present on VR.

**Comment by c0d3rb0y** [comment]
dang... is there any way to get it to work on a laptop other than getting an External GPU?

**Comment by GradiusLover2000** [comment]
either that or get a new machine.  you can get a vr ready machine for quite "cheap" these days, say, $600 to $800 USD?

**Comment by c0d3rb0y** [comment]
dangit :(

**Comment by c0d3rb0y** [comment]
actually is there any really cheap VR ready Laptops you can reccomend?

**Comment by c0d3rb0y** [comment]
sorry i know that isn't related to the issue at all.

**Comment by GradiusLover2000** [comment]
in all honestly you should be looking for a tower instead of a laptop.  cheap gaming laptops are a horrid option.  When I stated $600 to $800, I was speaking on the reigns of a custom built Tower.

**Comment by GradiusLover2000** [comment]
nevertheless if you just don't care, I personally always recommend a machine with:

Ryzen 5 3600 or better, 16GB DDR 3200MHz or better, and GTX 1650 SUPER or better, and not a mobile variant of it (such as M or MaxQ)

**Comment by Techjar** [comment]
Laptops are generally more expensive for the same specs.

**Comment by SetantaLP** [comment]
And additionally it's usually much more difficult than on a normal PC (or even hardly possible) to upgrade just some parts like the graphics card, because there isn't a lot of space inside. And besides that playing in VR needs a lot of resources, so depending on your specs, the cpu/gpu usage might be pretty high and the components inside will produce a lot of heat, which is something PCs usually handle much better than laptops because in a PC there is much more air between the components and by that components heat each other much less than in a laptop, that often passively cool via their surface.

**Comment by c0d3rb0y** [comment]
ok thanks
