### ISSUE TITLE
1.16.4 installer wont run 

### ISSUE THREAD

**Issue by emilgauti22** [jrbudda/Vivecraft_116#33]

**Comment by TheTrueForce** [comment]
This is about as unhelpful as it gets, mate. You need to give some actual information or we can't even begin to help.

**Comment by GradiusLover2000** [comment]
Provide a description or we cannot help.

you need to have Java RE installed to run the vivecraft installer.

**Comment by Espergium** [comment]
Have you tried running it

**Comment by mcdood81** [comment]
I am also having an issue with this.  so what is happenening is i had to update java then got installer to go but once i click install it doesnt do anything,,,, i am unsure if i need to also download the source code or what anyhelp would be great i just trying so hard to get the mindcraft vr to work for when my kids show up./

**Comment by GradiusLover2000** [comment]
you need to make sure the "modded" box is checked in the minecraft launcher's Installations tab, otherwise vivecraft will not show up as a selectable version.  @mcdood81 

so unless you are saying the installer would not run, in that case make sure the pc you are installing on is still connnected to the internet, and that you have run a vanilla instance of the minecraft version you are installing at least once.

**Comment by mcdood81** [comment]
Ok forgive me i am unsure where the modded button is in the minecraft launcher.  i am willing to see if that is able to help fix the issue.  Now when i open the installed i believe i have done everything correctly.  but when i click install that is when the java icon remains in the bottom tab the launcher closes and nothing happens..... as i am sitting here typing i just realized i may need to run installer as admin.  i will try that now and see if it fixes anything and will wait to hear more from you.  @GradiusLover2000
