### ISSUE TITLE
Cannot See Friend moving his arms in vr

### ISSUE THREAD

**Issue by MrKitCat1210** [jrbudda/Vivecraft_116#36]
i installed the non vr one and my friend is using the vr one he screenshared me hes in vr but i cant see his actions we both are using the same version of 1.16.4 and we are using the same install so why is this happening?

**Comment by TheTrueForce** [comment]
I presume you're on a server, though you haven't said. If the server does not have the plugin or server mod installed, it won't pass on the VR movement data.
If you're hosting the world on one of the clients, I suggest coming over to the discord and asking for help there. It'll be easier to deal with.
If you're on a Realm, you're out of luck. VR movement never worked on those and almost certainly never will.
If you're using some other server host, you'll need to switch to a Spigot server, and install Vivecraft Spigot Extensions. If you are using a free-of-charge host such as Aternos, good luck, because they often give you very little control.

Also, it would make your message infinitely easier to read if you used more punctuation than just a single question mark
