### ISSUE TITLE
Potential source of many mod conflicts?

### ISSUE THREAD

**Issue by AdeenDragon** [jrbudda/Vivecraft_116#53]
As far as I can tell, Vivecraft v6 is incompatible with any other mod that uses Mixins; the Minecraft launcher will crash on startup with exit code 0.  I've found that Bed Spreads, CraftTweaker, Fluid Physics, Hunter Illager, and Immersive Engineering are all incompatible; I assume many more are incompatible from the modpack that I am using, but after finding five different incompatibilities I figured that they probably had something in common.

CraftTweaker being incompatible is particularly devastating, as it is the most common way for modpack creators to customize and unifiy separate mods into a cohesive whole.

To reproduce, attempt to run Vivecraft with a mod that uses Mixins in the /mods folder.

Attached is my launcher_log.txt file
[launcher_log.txt](https://github.com/jrbudda/Vivecraft_116/files/5834313/launcher_log.txt)

**Comment by TheTrueForce** [comment]
Thre's a couple of things that could cause this. I doubt it's mixin itself, since some mods that use it have been compatible before. Rather, I suspect that it's simply due to most mods having updated past the Forge that Vivecraft is built to work with, and crashing due to the version difference.
Some mixin-based mods fail because they try to patch classes that Vivecraft also modifies, and has gotten to first.

**Comment by SetantaLP** [comment]
In genreal it would be helpful to post the game log (`latest.log` from the `logs` folder of the instance), not the launcher log, because the launcher log includes a bunch of info that is probably not relevant to problem.

Concerning the crash: that happens due to an `IllegalArgumentException` thrown by the mixin library because it could not read or find the mixin config file for the mod, that results in a `MixinInitialisationError`. That might be related to the fact that Vivecraft uses an older version of forge like @TheTrueForce mentioned (so maybe there has been a change to the config format since then that is not compatible with the mixin library forge uses), but it could also be some weird permission issue for the config files.

**Comment by AdeenDragon** [comment]
@SetantaLP Thanks for pointing out the better log file, I wasn't aware that it would be in the instance folder, rather than the .minecraft folder.
[latest.log](https://github.com/jrbudda/Vivecraft_116/files/5834708/latest.log)
Would log files from attempts to run other mods that seem to be incompatible be helpful?  My inexpert eyes see no difference between the log file that's generated from a crash due to Bed Spreads versus Immersive Engineering, but I could very well be missing something.

**Comment by SetantaLP** [comment]
It could be helpful, but the chances are high that (like in this case) it crashes with a `MixinInitialisationError` caused by an `IllegalArgumentException` thrown by the mixin library because it could not read or find the mixin config file for the mod.

So what you should do first is checking which version of the Mixin Library is required by the mods (according to the logs 0.8.2 is used), because it is possible that loading the file fails because the config file is not compatible with the version used here, even though an incompatible version would most likely already fail (or at least cause a warning in the log) when reading the mod manifest. If they require the same version, the crash would most likely be the same.

Besides that it could also help to check which version of the Mixin Library is used if you use the modpack/mods outside of vivecraft with the recommended version of forge.

**Comment by AdeenDragon** [comment]
I checked the other logs, and they crashed with the same `MixinInitialisationError`.

I booted up the modpack, [Brass](https://www.curseforge.com/minecraft/modpacks/brass) normally via the CurseForge launcher, without ViveCraft.  It does default to a newer version of Forge, specifically 35.1.36.  However, it doesn't use a different version of MIXIN; it uses 0.8.2.
[latest.log](https://github.com/jrbudda/Vivecraft_116/files/5835458/latest.log)

**Comment by SetantaLP** [comment]
That's pretty weird.
The only reason I could imagine (besides forge handling stuff different) why it doesn't work is, that for some reason an incorrect path is passed to the mixin lib or the path is relative to a directory that is not included in the classpath (or whatever the lib uses to resolve relative paths) but that's pretty unlikely since the same happened with the mods in `.minecraft/mods`.

But to rule that out completely you could download the mod from its official source and use it with a clean forge 35.1.36 profile in a clean game directory (to ensure that the mod works out of the box) and then do the same with forge 35.0.7.
If that doesn't work, we know that forge is the problem. If it does you should try the same with vivecraft. If that doesn't work, we know that either something in vivecraft itself or in the way vivecraft is launched is broken. If it works, we know that something in the pack is broken.

And by the way, make sure that Optfine is not in the mod folder since that would probably cause trouble later on.

**Comment by AdeenDragon** [comment]
Using an old version of Forge seems to be the problem; while Minecraft would load Immersive Engineering with forge 35.1.36, it wouldn't load it with forge [35.0.7](https://github.com/jrbudda/Vivecraft_116/files/5838465/latest.log).  Looking through the Forge changelog, it looks like something to do with Mixin was changed in in forge 35.0.16. 

While a installer for this version is unavailable, using the next available version, forge 35.1.4, results in a successful boot.  Using forge [35.0.14](https://github.com/jrbudda/Vivecraft_116/files/5838523/latest.log) results in the same crash as before. 

Moving over to Vivecraft, using forge [35.1.4](https://github.com/jrbudda/Vivecraft_116/files/5838623/Vivecraft_Forge_35.1.4.2.log) does result in a successful boot! I was able to get into a creative world and place some modded blocks down.  Interestingly, using Vivecraft with forge [35.1.36](https://github.com/jrbudda/Vivecraft_116/files/5838685/Vivecraft_Forge_35.1.36.log) does not work; while the game loads, creating or loading a world crashes the game.

**Comment by SetantaLP** [comment]
Chunk loading doesn't directly sound like something Vivecraft itself changes, but more like something Optifine modifies, so it's probably more an optifine issue (and as far as I heard the version of optifine used by Vivecraft doesn't work with the current version of forge) that also affects Vivecraft.

Concerning possible issues: we only know that the parts of the code that are used during startup and during world loading have not been changed in a way that makes them completely incompatible with the way the code worked before. But that could still result in stuff silently not working, if forge has added a new hook into code, that is modified by Vivecraft.
In general possible issues heavily depend on what changes happened in forge since then. If the changes only affect classes that are not touched by vivecraft, you will experience no issues at all. If changes affect classes that are touched by vivecraft, it heavily depends on what has changed and on if the changed code is used while you play, because in Optifine and Vivecraft forge stuff is handled via Reflection to allow Optifine and Vivecraft to work without forge, but that means that whatever stuff like a changed parameter list for a function will not cause trouble until the corresponding code is executed. So you might get spontaneous crashes (e.g. if the parameter list of one of the forge methods called from such code has changed), things might simply not work silently (e.g. if a new hook has been added), which can cause trouble later on if a mod relies on that, or you might experience no issues at all (if the affected code is not used while you play or if the changes don't affect other code).

**Comment by AdeenDragon** [comment]
Using IntelliJ I can find exactly what changes were made between Forge versions.  How can I find which classes Vivecraft/Optifine change?  I assume that if the changes made between Forge versions don't overlap with what Vivecraft and Optifine change, there shouldn't be any further issues.

**Comment by Esras** [comment]
To chime in, I was testing with the mod pack Valhesia and All The Mods 6, I get a giant stack trace (thanks, Java...) that ends with `Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector getDismountKeyLocalizedText(Lnet/minecraft/client/settings/KeyBinding;)Lnet/minecraft/util/text/ITextComponent; in randompatches.mixins.json:client.keybindings.ClientPlayNetHandlerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap randompatches.refmap.json`

Testing different Forge versions, version `35.1.10` runs, but version `35.1.11` crashes. Hope this helps someone...

**Comment by AdeenDragon** [comment]
With the release of Vivecraft 1.16.5 v7 and it's update to Forge 36.0.1 this issue is solved.
