### ISSUE TITLE
Keyboard and Mouse Bindings SteamVR

### ISSUE THREAD

**Issue by ThePreviousOne** [jrbudda/Vivecraft_116#59]
I have noticed that some actions still only work on keyboard, or are just easier. Dismounting from boats or horses is a good example, but also I generally play with mods and cannot map all the needed actions without overlaps. So I was wondering if keyboard and mouse binding options could be added to the choices for 'Global' keybinding in SteamVR.

**Comment by Techjar** [comment]
I fail to see how any of what you mentioned is improved by being able to directly emulate keyboard keys. The binding code already internally does that to maximize compatibility with mods, so there is functionally no difference and we'd just be making a big mess for no reason. Also, dismounting is tied to the sneak binding (just like in vanilla).

**Comment by ThePreviousOne** [comment]
> I fail to see how any of what you mentioned is improved by being able to directly emulate keyboard keys. The binding code already internally does that to maximize compatibility with mods, so there is functionally no difference and we'd just be making a big mess for no reason.

Sneak != shift, and Attack != Left Click, etc. So shift+left-click, shift+right-click, shift+up, etc, all require separate bindings rather than just sneaking and pressing whatever button. Also to a lesser extent some mod actions are GUI only and some are not so that gets hard to manage. Plus 'Ingame' actions are superseded by 'Mod' ones (I think) and those by 'Global' ones which can be difficult in itself to plan out when mapping them.

> Also, dismounting is tied to the sneak binding (just like in vanilla).

Even so I should not have to bind a sneak key simply for this reason when I can, for any other purpose physically crouch down 'Sneaking'.

**Comment by Techjar** [comment]
> Sneak != shift, and Attack != Left Click, etc. So shift+left-click, shift+right-click, or ctrl+something, all require separate bindings rather than just sneaking and pressing whatever button.

All in-world "shift click" actions in Minecraft are actually tied to the sneak key, so it's really "sneak click" rather than "shift click". If a mod has hard-coded use of Shift or Ctrl in-world, they are doing it wrong and I don't care. Everything should be a binding. As for GUIs, there already exists Shift, Ctrl and Alt bindings in the GUI action set.

> Also to a lesser extent some mod actions are GUI only and some are not so that gets hard to manage.

There is actually an undocumented system to put mod bindings in a different action set than the default "Modded" one. I'll get the instructions for that later if you want.

> Plus 'Ingame' actions are superseded by 'Mod' ones (I think) and those by 'Global' ones which can be difficult in itself to plan out when mapping them.

Yeah this is inherent to using a mod pack with 100 bindings on controllers with only 10 buttons. I don't see how being able to bind keyboard keys directly would help with this. As for overlaps, there is no priority, if multiple bindings share the same button then they will all be triggered.

> Even so I should not have to bind a sneak key simply for this reason when I can, for any other purpose physically crouch down 'Sneaking'.

We decided to not have roomscale sneaking exit vehicles because it was way too easy to accidentally trigger it. You wouldn't even be able to sit down during a minecart ride, or something like that.

**Comment by ThePreviousOne** [comment]
Ok point taken, still might give it a shot myself for testing, but I will keep this in mind

**Comment by ThePreviousOne** [comment]
> If a mod has hard-coded use of Shift or Ctrl in-world, they are doing it wrong and I don't care.

I did't mean hardcoded, but contextual thing like while holding X or looking/cursor focus on Y
